#!/usr/bin/env bash

set -e

# Sort imports one per line, so autoflake can remove unused imports
isort --recursive  --force-single-line-imports unasyncer tests

autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place unasyncer tests
black unasyncer tests
isort --recursive unasyncer tests
